# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.9.4"
Vagrant.configure("2") do |config|
  # Vagrant ssh private key
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Linux Router
  config.vm.define "linuxrouter", primary: true do |core|
    core.vm.box = "centos/7"
    core.vm.hostname = "linuxrouter"
    core.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)", ip: "192.168.1.5"
    core.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    core.vm.provision :shell, path: "../init.sh"
    core.vm.provision :shell, path: "../vboxguest.sh"
    core.vm.provision :shell, path: "../zabbix.sh"
  end
end
