# -*- mode: ruby -*-
# vi: set ft=ruby :

domain = "shibusa.io"

Vagrant.require_version ">= 1.9.3"
Vagrant.configure("2") do |config|
  # Vagrant ssh private key
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # DNS Primary and Secondary
  (1..2).each do |i|
    config.vm.define "dns0#{i}" do |core|
      core.vm.box = "centos/7"
      core.vm.hostname = "dns0#{i}.#{domain}"
      core.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      core.vm.provision :shell, path: "../init.sh"
      core.vm.provision :shell, path: "../vboxguest.sh"
    end
  end

  # Network Monitor server
  config.vm.define "netmon" do |core|
    core.vm.box = "centos/7"
    core.vm.hostname = "netmon.#{domain}"
    core.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    core.vm.provision :shell, path: "../init.sh"
    core.vm.provision :shell, path: "../vboxguest.sh"
  end
end
