# -*- mode: ruby -*-
# vi: set ft=ruby :

domain = "shibusa.io"
clustercount = 3

Vagrant.require_version ">= 1.9.4"
Vagrant.configure("2") do |config|
  # Vagrant ssh private key
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]
  config.ssh.insert_key = false

  # Chef server
  config.vm.define "core", primary: true do |core|
    core.vm.box = "centos/7"
    core.vm.hostname = "core.#{domain}"
    core.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/"
    core.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
    core.vm.provision :shell, path: "../init.sh"
    core.vm.provision :shell, path: "../vboxguest.sh"
    core.vm.provision :shell, path: "../rubycompile.sh"
    core.vm.provision :shell, path: "../chefserver.sh"
    core.vm.provision :shell, path: "../chefdownloads.sh"
  end

  # Chef clients
  (1..clientcount).each do |i|
    config.vm.define "node-#{i}" do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = "node-#{i}.#{domain}"
      node.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      node.vm.provision :shell, path: "../vboxguest.sh"
    end
  end
end
